language: php

php:
  - 5.5
  - 5.6
  - 7

services:
  - mysql
  - mongodb
  - postgresql

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES
  - psql -c 'create database event_store_adapter_benchmarks;' -U postgres

script:
  - php ./bin/run_benchmark.php
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
